# This python script takes as input pairs of excel spreadsheets containing tokens
# of a lexical unit from Frantext and from MCVF. It combines the data for each
# LU into an xml file matching the necessary lu.xml format readable by the
# FrameNet Annotation Tool. Tokens are separated by century within the file.
# It assigns a sentence ID to each token, concatenating it with the sentence text.
# It also produces another xml file matching sentid's to source metadata (reference and genre)

# Create dictionary of lexical units and their frames
ludict = {
    "coustage":"FR_Spending",
    "coustageux":"FR_Spending",
    "coustance":"FR_Spending",
    "coustement":"FR_Spending",
    "cout":"FR_Spending",
    "couter":"FR_Spending",
    "deboursement":"FR_Spending",
    "debourser":"FR_Spending",
    "depense":"FR_Spending",
    "depenser":"FR_Spending",
    "encouter":"FR_Spending",
    "frais":"FR_Spending",
    "fuer":"FR_Spending",
    "surcout":"FR_Spending",
    "couteux":"FR_Spending",
    "depens":"FR_Spending",
    "prix":"FR_Spending",
    "argentdebourse":"FR_Spending",
    "tirerdesabourse":"FR_Spending",
    "emploidesonbien":"FR_Spending",
    "employersonbien":"FR_Spending",
    "fairedeladepense":"FR_Spending",
    "fairedesfrais":"FR_Spending",
    "debourse":"FR_Spending",
    "cher":"FR_Spending",
    "dispendieux":"FR_Spending",
    "onereux":"FR_Spending",
    "quicoutebeaucoup":"FR_Spending",
    "quiestdegrandprix":"FR_Spending",
    "attribuer":"FR_Attributing_cause",
    "attribution":"FR_Attributing_cause",
    "explication":"FR_Attributing_cause",
    "expliquer":"FR_Attributing_cause",
    "imputable":"FR_Attributing_cause",
    "imputer":"FR_Attributing_cause",
    "justifier":"FR_Attributing_cause",
    "mettresurlecomptede":"FR_Attributing_cause",
    "aveu":"Reveal_secret",
    "avouer":"Reveal_secret",
    "balancer":"Reveal_secret",
    "cafeter":"Reveal_secret",
    "confes":"Reveal_secret",
    "confesser":"Reveal_secret",
    "confession":"Reveal_secret",
    "confier":"Reveal_secret",
    "devoilement":"Reveal_secret",
    "devoiler":"Reveal_secret",
    "divulgation":"Reveal_secret",
    "divulguer":"Reveal_secret",
    "ebruitement":"Reveal_secret",
    "ebruiter":"Reveal_secret",
    "revelation":"Reveal_secret",
    "reveler":"Reveal_secret",
    "seconfier":"Reveal_secret",
    "convenir":"Reveal_secret",
    "demeurerdaccord":"Reveal_secret",
    "faireaveu":"Reveal_secret",
    "denonciation":"Reveal_secret",
    "denoncer":"Reveal_secret",
    "fairetomberlevoile":"Reveal_secret",
    "leverlevoile":"Reveal_secret",
    "mettreadecouvert":"Reveal_secret",
    "mettreaujour":"Reveal_secret",
    "mettreenevidence":"Reveal_secret",
    "rendrepublic":"Reveal_secret",
    "eventer":"Reveal_secret",
    "trahirunsecret":"Reveal_secret",
    "delateur":"Reveal_secret",
    "delation":"Reveal_secret",
}

for x,y in ludict.items():
    lu = x
    frame = y
    # Indicate the directories for each frame where output files for each LU are stored
    path = f'C:\\Users\\Jim\\OneDrive\\Documents\\Dissertation\\Data\\{frame}\\MCVF data\\{lu}.out'
